# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('verifed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('legal_entity', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.BooleanField()),
                ('snils', models.BooleanField()),
                ('ndfl', models.BooleanField()),
                ('employment_history', models.BooleanField()),
                ('insurance', models.BooleanField()),
                ('estate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.CharField(choices=[('rub', 'Рублей'), ('usb', '€'), ('usd', '$')], max_length=100)),
                ('amount_begin', models.IntegerField(null=True, verbose_name='Минимальная сумма займа')),
                ('amount_end', models.IntegerField(null=True, verbose_name='Максимальная сумма займа')),
                ('time', models.CharField(choices=[('days', 'Дней'), ('weeks', 'Недель'), ('months', 'Месяцев'), ('years', 'Лет')], max_length=100)),
                ('time_begin', models.IntegerField(null=True, verbose_name='Минимальный возраст')),
                ('time_end', models.IntegerField(null=True, verbose_name='Максимальный возраст')),
                ('loan_begin', models.IntegerField(null=True, verbose_name='Минимальная процентная ставка')),
                ('loan_end', models.IntegerField(null=True, verbose_name='Максимальная процентная ставка')),
                ('creditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creditor.Creditor')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_begin', models.IntegerField()),
                ('age_end', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('credit_history', models.CharField(max_length=200)),
                ('bail', models.BooleanField()),
                ('pledge', models.BooleanField()),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditor.Documents')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditor.Requirements'),
        ),
    ]
