# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('legal_entity', models.BooleanField()),
                ('address', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.BooleanField()),
                ('snils', models.BooleanField()),
                ('ndfl', models.BooleanField()),
                ('employment_history', models.BooleanField()),
                ('insurance', models.BooleanField()),
                ('estate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Amountrange')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Loanrange')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_begin', models.IntegerField()),
                ('age_end', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('credit_history', models.CharField(max_length=200)),
                ('bail', models.BooleanField()),
                ('pledge', models.BooleanField()),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.Documents')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.Requirements'),
        ),
        migrations.AddField(
            model_name='offer',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Timerange'),
        ),
    ]
