# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='borrower.Offer'),
        ),
    ]
