# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_borrower_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='borrower.Borrower'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='main.Contacts'),
        ),
    ]
