# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0003_auto_20170212_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
