# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0006_auto_20170212_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='verifed',
            field=models.BooleanField(default=False),
        ),
    ]
