# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0007_auto_20170212_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='contacts',
        ),
    ]
