# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0008_remove_borrower_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='loan',
        ),
        migrations.AddField(
            model_name='offer',
            name='amount_b',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='amount_e',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='loan_b',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='loan_e',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='time_b',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='time_e',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.CharField(choices=[('rub', 'Рублей'), ('usb', '€'), ('usd', '$')], max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='time',
            field=models.CharField(choices=[('days', 'Дней'), ('weeks', 'Недель'), ('months', 'Месяцев'), ('years', 'Лет')], max_length=100),
        ),
    ]
