# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0009_auto_20170212_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='amount_b',
            new_name='amount_begin',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='amount_e',
            new_name='amount_end',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='loan_b',
            new_name='loan_begin',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='loan_e',
            new_name='loan_end',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='time_b',
            new_name='time_begin',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='time_e',
            new_name='time_end',
        ),
    ]
