# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('choice', models.CharField(blank=True, choices=[('mail', 'E-mail'), ('phone', 'Телефон'), ('skype', 'Skype'), ('vk', 'Vkontakte')], default='mail', max_length=100, null=True)),
                ('creditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creditor.Creditor')),
            ],
        ),
    ]
