# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amountrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rub', 'Рублей'), ('usb', '€'), ('usd', '$')], max_length=100)),
                ('begin', models.ImageField(upload_to='')),
                ('end', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_value', models.CharField(max_length=20)),
                ('contact_type', models.CharField(choices=[('mail', 'E-mail'), ('phone', 'Телефон'), ('skype', 'Skype'), ('vk', 'Vkontakte')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loanrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('days', 'Дней'), ('weeks', 'Недель'), ('months', 'Месяцев'), ('years', 'Лет')], max_length=100)),
                ('begin', models.ImageField(upload_to='')),
                ('end', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Timerange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('king', models.CharField(choices=[('days', 'Дней'), ('weeks', 'Недель'), ('months', 'Месяцев'), ('years', 'Лет')], max_length=100)),
                ('begin', models.ImageField(upload_to='')),
                ('end', models.ImageField(upload_to='')),
            ],
        ),
    ]
