# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_type',
            new_name='name',
        ),
    ]
