# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170211_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(blank=True, choices=[('mail', 'E-mail'), ('phone', 'Телефон'), ('skype', 'Skype'), ('vk', 'Vkontakte')], max_length=100, null=True),
        ),
    ]
