# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0009_auto_20170212_0700'),
        ('main', '0004_contacts_borrower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amountrange',
        ),
        migrations.DeleteModel(
            name='Loanrange',
        ),
        migrations.DeleteModel(
            name='Timerange',
        ),
    ]
