# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170212_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='name',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_value',
            new_name='value',
        ),
    ]
